---
title: "Untitled"
author: "Julian Philip S. Quijano"
date: "2025-04-08"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Time Between Student Arrivals at the FEU Library (3rd Floor) from 8:38 AM to 9:38 AM

```{r}
library(readxl)
library(ggplot2)
data = read_excel("FA7 - Data.xlsx")
mean = 1.1173
lambda = 1/mean
x = seq(0, 48, by = 1)

pdf = dexp(x, rate = lambda)
cdf = pexp(x, rate = lambda)

pdf_data = data.frame(x = x, pdf = pdf)

ggplot(pdf_data, aes(x = x, y = pdf)) +
  geom_line(color = "blue") +
  labs(title = "Probability Density Function of Exponential Distribution",
       x = "x",
       y = "Density") +
  theme_minimal()

time_intervals = as.numeric(data$...5[3:50])

ggplot(data.frame(time_intervals), aes(x = time_intervals)) + geom_histogram(binwidth = 1, fill = "blue", color = "black") + labs(title = "Histogram of Time Intervals", x = "Time Intervals", y = "Frequency") + theme_minimal()
```

## The average wait time per minute $\mu$ = 1.1173 and there is an expected $\lambda$ = 0.895 student arrivals per minute.
